### ISSUE TITLE
Scrolling through long list of items skips frames and lags

### ISSUE THREAD

**Issue by BlackCorsair** [JoeLago/MHGUDB-iOS#1]
Hi,

Scrolling through the app on an iPhone 8 lags pretty bad for the first time in a long list of items. Looking at your Trello I think that it may be caused because of image catching.

Here's some proof, although probably you are aware of the issue:
[zip of the video](https://github.com/JoeLago/MHGUDB-iOS/files/3565551/mhgu.scrolling.issue.MP4.zip)

I don't have any experience with iOS development, but I'll check the code to see if I can help you with this.

**Comment by JoeLago** [comment]
So I actually tackled this a while ago, it hiccups when it tries to load images for the first time. The easy fix was just to load all the images in the background at startup so that UIKit does whatever magic it does to cache the images. https://github.com/JoeLago/MHGUDB-iOS/commit/017292fb4446a7660e425a1c43679db730ecfff0

This also speeds up first loads on screens pretty dramatically too. I just never got around to putting these updates on the app store. Maybe Now that I'm messing around with the MH World app I'll take a little time to get the updates in the app store.  

Appreciate the report! Sorry for the delay.

**Comment by BlackCorsair** [comment]
Thank you for your efforts :)
